.TH LIBTTOY 3
.SH NAME
libttoy \- library for developing plugins for the ttoy terminal emulator
.SH DESCRIPTION
The \fBlibttoy\fR library exposes a plugin API which can be used to develop
custom plugins for use with the \fBttoy\fR(1) terminal emulator program. These
plugins are called \fItoys\fR within the context of the \fBttoy\fR program.

Since \fBttoy\fR is currently in the early stages of development, the
\fBlibttoy\fR library interface is still far from being finalized. This man
page is a stub that will be expanded as \fBlibttoy\fR matures. If you are
interested in developing plugins for \fBttoy\fR, please contact the \fBttoy\fR
developers directly.
